<?php

// Add metadata for your app here
return [
    'default' => [
        'title' => 'TSNC',
        'description' => 'Generated by create TSNC',
    ],
    'users' => [
        'title' => 'Users',
        'description' => 'User management',
    ],
];
